services:
  postgres:
    image: postgres:latest
    container_name: UberDBServerImage
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: devdb
    
